language: node_js
sudo: false
node_js:
  - "6"
  - "8"
  - "10"
before_script:
  - npm install
  - cd packages/skema
  - npm install
  - cd -
  - cd packages/basic
  - npm install
  - cd -
after_success:
  - npm run report-cov
